# # multiple_exceptions_in_single_clause
# ___ divide_numbers
#     loop = T...
#     w___ ?
#         t__
#             first_number _ fl.. inp..('First number: '))
#             second_number = fl.. inp...('Second number: '))
#             print('Result:', f.. / s..)
#             ? _ F..
#         e____  V..., Z... a_ error
#             print('Error:', ?)
#             print('Please try again')
#             print()
#             ? _ T..
#
# __ _______ __ _____
#     ?
